#' Visualize Association Rules as a Network Graph
#'
#' This function visualizes a set of association rules as a network graph using
#' the `ggraph` package. Nodes represent items and edges represent rules between items.
#'
#' @param rules An object of class "rules" generated by the `apriori` function from the `arules` package.
#' @param rule.size A character string specifying the measure to use for node size. Options are "support", "confidence", or "lift".
#' @param rule.color A character string specifying the measure to use for node color. Options are "support", "confidence", or "lift".
#' @param min.val A character string specifying the color for the minimum value in the color gradient.
#' @param max.val A character string specifying the color for the maximum value in the color gradient.
#' @param edge_col A character string specifying the color of the edges.
#' @param num_rules An integer specifying the maximum number of rules to visualize. Default is 10.
#'
#' @return A ggplot2 object representing the network graph of association rules.
#' @importFrom arules apriori
#' @importFrom ggraph geom_edge_link geom_node_point geom_node_text circle
#' @importFrom arulesViz associations2igraph
#' @importFrom ggplot2 aes_string scale_color_gradient scale_size labs arrow unit
#' @export
#'

fig_rules_network <- function(rules,
                               rule.size = "support",
                               rule.color = "confidence",
                               min.val = "#FFDEAD",
                               max.val = "blue",
                               edge_col = "blue",
                               num_rules = 10
){
  # 动态设置图例标签
  size_label <- switch(rule.size,
                       "support" = "\u652f\u6301\u5ea6",
                       "confidence" = "\u7f6e\u4fe1\u5ea6",
                       "lift" = "\u63d0\u5347\u5ea6")

  color_label <- switch(rule.color,
                        "support" = "\u652f\u6301\u5ea6",
                        "confidence" = "\u7f6e\u4fe1\u5ea6",
                        "lift" = "\u63d0\u5347\u5ea6")
  t <- arulesViz::associations2igraph(rules)
  # 绘制图形
  p <- plot(rules, method = "graph",
            control = list(
              edges = ggraph::geom_edge_link(
                end_cap = ggraph::circle(4, "mm"),
                start_cap = ggraph::circle(4, "mm"),
                color = edge_col,
                arrow = arrow(length = unit(2, "mm"), angle = 20, type = "closed"),
                alpha = .2
              ),
              nodes = ggraph::geom_node_point(aes_string(size = rule.size, color = rule.color)),
              nodetext = ggraph::geom_node_text (aes_string(label = "label"), alpha = .8,
                                                repel = TRUE, size = 6, family = "SimSun")
            ),
            limit = num_rules
  ) +
    scale_color_gradient(low = min.val, high = max.val) +
    scale_size(range = c(4, 8)) +
    labs(size = size_label, color = color_label)


  return(p)
}
